---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cypress/browsers
    tag: 'node12.14.1-chrome83-ff77'

inputs:
  - name: source

outputs:
  - name: test-results

params:
  CYPRESS_TOKEN_URL: https://login.testing-boclips.com/auth/realms/boclips/protocol/openid-connect/token
  CYPRESS_API_BASE_URL: https://api.testing-boclips.com
  CYPRESS_HQ_BASE_URL: https://hq.testing-boclips.com
  CYPRESS_FRONTEND_BASE_URL: https://publishers.testing-boclips.com
  CYPRESS_TEACHERS_BASE_URL: https://teachers.testing-boclips.com
  CYPRESS_PUBLISHERS_BASE_URL: https://tazingo.testing-boclips.com
  CYPRESS_LTI_TOOL_CONSUMER_EMULATOR_URL: https://ltiapps.net/test/tc.php
  CYPRESS_LTI_LAUNCH_URL: https://lti.testing-boclips.com/v1p1
  CYPRESS_HQ_USERNAME:
  CYPRESS_HQ_PASSWORD:
  CYPRESS_FRONTEND_USERNAME:
  CYPRESS_FRONTEND_PASSWORD:
  CYPRESS_OPERATOR_USERNAME:
  CYPRESS_OPERATOR_PASSWORD:
  CYPRESS_SELECTED_VIDEOS_TEST_USERNAME:
  CYPRESS_SELECTED_VIDEOS_TEST_PASSWORD:
  CYPRESS_LTI_CONSUMER_KEY:
  CYPRESS_LTI_CONSUMER_SECRET:
  PERCY_TOKEN:
  SPEC:

run:
  path: source/pipelines/scripts/run

caches:
  - path: ../../../root/.cache
  - path: ../../../root/.npm
