---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cypress/base
    tag: "10"

inputs:
  - name: source

outputs:
  - name: test-results

params:
  CYPRESS_OPERATOR_USERNAME:
  CYPRESS_OPERATOR_PASSWORD:
  CYPRESS_BACKOFFICE_USERNAME:
  CYPRESS_BACKOFFICE_PASSWORD:
  CYPRESS_BACKOFFICE_BASE_URL:

  CYPRESS_TEACHERS_USERNAME:
  CYPRESS_TEACHERS_PASSWORD:
  CYPRESS_TEACHERS_BASE_URL:

  CYPRESS_FRONTEND_USERNAME:
  CYPRESS_FRONTEND_PASSWORD:
  CYPRESS_FRONTEND_BASE_URL:

run:
  path: source/pipelines/scripts/run

caches:
  - path: ../../../root/.cache
  - path: ../../../root/.npm
