#!/usr/bin/env bash

npm_script=$1

produce_output () {
    mkdir -p source/cypress/{screenshots,videos}
    cd "source/cypress" || exit
    timestamp="$(date --rfc-3339=seconds)"
    results_dir="test-results-$timestamp.tar"
    mkdir "$results_dir"
    cp -a screenshots videos "$results_dir/"
    tar -cf "../../test-results/results.tar" \
        "$results_dir"
}
trap produce_output EXIT

(
cd source || exit 1
npm ci || exit 1

npm run "$npm_script" -- \
    --browser=chrome \
    --spec="$SPEC" \
    --config video=false
)
